<a href="https://colab.research.google.com/github/Monserrat555/proyecto2/blob/main/clasificadores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Para leer el documento que necesita el codigo
from google.colab import drive
drive.mount('/content/sample_data/cancer.csv')

Mounted at /content/drive


In [1]:
# Gopar Iniesta Tania Monserrat

# Todo lo que importamos
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
import warnings

# Ignorar advertencias para que no interrumpan la ejecución
warnings.filterwarnings("ignore", category=FutureWarning)
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings("ignore", category=ConvergenceWarning)

# Clase de clasificadores que necesitamos
class Clasificadores:
    def __init__(self):
        self.modelos = {
            "Regresión Logística": LogisticRegression(max_iter=200),
            "k-NN": KNeighborsClassifier(n_neighbors=3),
            "SVM": SVC(kernel='linear'),
            "Árbol de Decisión": DecisionTreeClassifier(),
            "Random Forest": RandomForestClassifier()
        }
# Aqui entrenamos el codigo y evaluamos
    def entrenar(self, X_train, y_train):
        for nombre, modelo in self.modelos.items():
            try:
                modelo.fit(X_train, y_train)
                print(f"Modelo {nombre} entrenado correctamente.")
            except Exception as e:
                print(f"Error al entrenar el modelo {nombre}: {e}")

    def evaluar(self, X_test, y_test):
        resultados = {}
        for nombre, modelo in self.modelos.items():
            try:
                y_pred = modelo.predict(X_test)
                exactitud = accuracy_score(y_test, y_pred)
                precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
                resultados[nombre] = {
                    "Exactitud": exactitud,
                    "Precisión": precision
                }
                print(f"{nombre}: Exactitud = {exactitud * 100:.2f}%, Precisión = {precision * 100:.2f}%")

                print("Matriz de confusión:")
                print(confusion_matrix(y_test, y_pred))
                print("Reporte de clasificación:")
                print(classification_report(y_test, y_pred))
            except Exception as e:
                print(f"Error al evaluar el modelo {nombre}: {e}")
        return resultados

# Función para cargar datos desde un archivo CSV
def cargar_datos(ruta):
    try:
        data = pd.read_csv(ruta)
        print(f"Datos cargados correctamente desde {ruta}.")
        return data
    except Exception as e:
        print(f"Error al cargar los datos: {e}")
        return None

# Preprocesamiento de datos
def preprocesar_datos(datos):
    try:
        # Convertir etiquetas categóricas a numéricas
        labelencoder = LabelEncoder()

        # Identificar columna de etiquetas (última columna)
        y = datos.iloc[:, -1]

        # Verificar si la columna de etiquetas es continua
        if y.dtype in ['int64', 'float64']:
            # Discretizar etiquetas continuas en bins categóricos
            y = pd.cut(y, bins=3, labels=[0, 1, 2]).astype(int)

        # Actualizar etiquetas en los datos
        datos.iloc[:, -1] = y

        # Convertir columnas categóricas de características si las hay
        for col in datos.columns[:-1]:
            if datos[col].dtype == 'object':
                datos[col] = labelencoder.fit_transform(datos[col])

        print("Datos preprocesados correctamente.")
        return datos
    except Exception as e:
        print(f"Error al preprocesar los datos: {e}")
        return None

# Punto de entrada principal
if __name__ == "__main__":
    # Ruta del archivo
    ruta = '/content/sample_data/cancer.csv'

    # Cargar datos
    datos = cargar_datos(ruta)

    if datos is not None:
        # Preprocesar datos
        datos = preprocesar_datos(datos)

        if datos is not None:
            try:
                # Suponiendo que las columnas finales son características y etiquetas
                X = datos.iloc[:, :-1].values
                y = datos.iloc[:, -1].values

                # Escalar las características
                scaler = StandardScaler()
                X = scaler.fit_transform(X)

                # Dividir los datos en conjuntos de entrenamiento y prueba
                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

                # Crear instancia de clasificadores
                clasificadores = Clasificadores()

                # Entrenar modelos
                clasificadores.entrenar(X_train, y_train)

                # Evaluar modelos
                resultados = clasificadores.evaluar(X_test, y_test)

                # Mostrar resumen
                print("Resultados finales:")
                for nombre, metricas in resultados.items():
                    print(f"{nombre}: Exactitud = {metricas['Exactitud'] * 100:.2f}%, Precisión = {metricas['Precisión'] * 100:.2f}%")
            except Exception as e:
                print(f"Error al procesar los datos: {e}")

Datos cargados correctamente desde /content/sample_data/cancer.csv.
Datos preprocesados correctamente.
Modelo Regresión Logística entrenado correctamente.
Modelo k-NN entrenado correctamente.
Modelo SVM entrenado correctamente.
Modelo Árbol de Decisión entrenado correctamente.
Modelo Random Forest entrenado correctamente.
Regresión Logística: Exactitud = 96.00%, Precisión = 94.88%
Matriz de confusión:
[[88  0  0]
 [ 3  8  0]
 [ 0  1  0]]
Reporte de clasificación:
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98        88
         1.0       0.89      0.73      0.80        11
         2.0       0.00      0.00      0.00         1

    accuracy                           0.96       100
   macro avg       0.62      0.58      0.59       100
weighted avg       0.95      0.96      0.95       100

k-NN: Exactitud = 91.00%, Precisión = 88.78%
Matriz de confusión:
[[87  1  0]
 [ 7  4  0]
 [ 0  1  0]]
Reporte de clasificación:
              precisio

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/m

              precision    recall  f1-score   support

         0.0       0.93      0.98      0.96        88
         1.0       0.62      0.45      0.53        11
         2.0       0.00      0.00      0.00         1

    accuracy                           0.91       100
   macro avg       0.52      0.48      0.49       100
weighted avg       0.89      0.91      0.90       100

Random Forest: Exactitud = 93.00%, Precisión = 91.47%
Matriz de confusión:
[[87  1  0]
 [ 5  6  0]
 [ 0  1  0]]
Reporte de clasificación:
              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97        88
         1.0       0.75      0.55      0.63        11
         2.0       0.00      0.00      0.00         1

    accuracy                           0.93       100
   macro avg       0.57      0.51      0.53       100
weighted avg       0.91      0.93      0.92       100

Resultados finales:
Regresión Logística: Exactitud = 96.00%, Precisión = 94.88%
k-NN: Exactitud = 91

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
